-- Port Operations: Database Setup
CREATE DATABASE IF NOT EXISTS MANUFACTURING_PORT_OPS;

CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.RAW;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.CURATED;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.AI;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.ML;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.SEARCH;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_PORT_OPS.APP;

USE DATABASE MANUFACTURING_PORT_OPS;
USE WAREHOUSE CORTEX;
