-- Port Operations: Raw Tables
USE SCHEMA MANUFACTURING_PORT_OPS.RAW;

CREATE OR REPLACE TABLE VESSELS (
    VESSEL_ID NUMBER,
    VESSEL_NAME VARCHAR,
    VESSEL_TYPE VARCHAR,
    FLAG VARCHAR,
    CAPACITY_TEU NUMBER,
    CURRENT_STATUS VARCHAR,    -- BERTHED, ANCHORED, IN_TRANSIT, DEPARTED
    ASSIGNED_TERMINAL VARCHAR,
    ARRIVAL_TIME TIMESTAMP,
    CARGO_VALUE NUMBER(12,2),
    PRIORITY VARCHAR
);

CREATE OR REPLACE TABLE TERMINALS (
    TERMINAL_ID VARCHAR,
    TERMINAL_NAME VARCHAR,
    BERTH_COUNT NUMBER,
    MAX_VESSEL_SIZE VARCHAR,
    CRANE_COUNT NUMBER,
    OPERATING_HOURS VARCHAR,
    SPECIALIZATION VARCHAR
);

CREATE OR REPLACE TABLE BERTH_ASSIGNMENTS (
    ASSIGNMENT_ID VARCHAR,
    VESSEL_ID NUMBER,
    TERMINAL_ID VARCHAR,
    BERTH_NUMBER NUMBER,
    ARRIVAL TIMESTAMP,
    DEPARTURE TIMESTAMP,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE PORT_EVENTS (
    EVENT_ID VARCHAR,
    VESSEL_ID NUMBER,
    TERMINAL_ID VARCHAR,
    EVENT_TYPE VARCHAR,
    EVENT_TIME TIMESTAMP,
    DETAILS VARCHAR,
    SEVERITY VARCHAR
);

CREATE OR REPLACE TABLE CARGO_MANIFESTS (
    MANIFEST_ID VARCHAR,
    VESSEL_ID NUMBER,
    CARGO_TYPE VARCHAR,
    QUANTITY_TEU NUMBER,
    WEIGHT_TONS NUMBER,
    VALUE_USD NUMBER(12,2),
    HAZMAT_CLASS VARCHAR,
    DESTINATION VARCHAR
);

CREATE OR REPLACE TABLE PORT_REGULATIONS (
    DOC_ID VARCHAR,
    TITLE VARCHAR,
    CATEGORY VARCHAR,
    CONTENT VARCHAR,
    EFFECTIVE_DATE DATE
);
