-- Port Operations: External Stage & Data Loading
USE SCHEMA MANUFACTURING_PORT_OPS.RAW;

CREATE OR REPLACE STAGE PORT_OPS_S3_STAGE
    URL = 's3://sg-manufacturing-demos-2026/port-ops/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO VESSELS FROM @PORT_OPS_S3_STAGE/vessels/;
COPY INTO TERMINALS FROM @PORT_OPS_S3_STAGE/terminals/;
COPY INTO BERTH_ASSIGNMENTS FROM @PORT_OPS_S3_STAGE/berth_assignments/;
COPY INTO PORT_EVENTS FROM @PORT_OPS_S3_STAGE/port_events/;
COPY INTO CARGO_MANIFESTS FROM @PORT_OPS_S3_STAGE/cargo_manifests/;
COPY INTO PORT_REGULATIONS FROM @PORT_OPS_S3_STAGE/port_regulations/;
