-- Port Operations: Dynamic Tables
USE SCHEMA MANUFACTURING_PORT_OPS.CURATED;

CREATE OR REPLACE DYNAMIC TABLE TERMINAL_STATUS
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    t.TERMINAL_ID,
    t.TERMINAL_NAME,
    t.BERTH_COUNT,
    COUNT(CASE WHEN b.DEPARTURE IS NULL THEN 1 END) AS OCCUPIED_BERTHS,
    t.BERTH_COUNT - COUNT(CASE WHEN b.DEPARTURE IS NULL THEN 1 END) AS FREE_BERTHS,
    LEAST(100, ROUND(COUNT(CASE WHEN b.DEPARTURE IS NULL THEN 1 END) / t.BERTH_COUNT * 100, 1)) AS UTILIZATION_PCT,
    COUNT(CASE WHEN v.CURRENT_STATUS = 'ANCHORED' AND v.ASSIGNED_TERMINAL = t.TERMINAL_ID THEN 1 END) AS VESSELS_QUEUED,
    AVG(CASE WHEN v.CURRENT_STATUS = 'ANCHORED' THEN DATEDIFF('hour', v.ARRIVAL_TIME, CURRENT_TIMESTAMP()) END) AS AVG_WAIT_HOURS
FROM RAW.TERMINALS t
LEFT JOIN RAW.BERTH_ASSIGNMENTS b ON t.TERMINAL_ID = b.TERMINAL_ID AND b.DEPARTURE IS NULL
LEFT JOIN RAW.VESSELS v ON t.TERMINAL_ID = v.ASSIGNED_TERMINAL
GROUP BY t.TERMINAL_ID, t.TERMINAL_NAME, t.BERTH_COUNT;

CREATE OR REPLACE DYNAMIC TABLE VESSEL_TRACKING
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    v.VESSEL_ID,
    v.VESSEL_NAME,
    v.VESSEL_TYPE,
    v.CURRENT_STATUS,
    v.ASSIGNED_TERMINAL,
    v.CARGO_VALUE,
    v.PRIORITY,
    v.CAPACITY_TEU,
    DATEDIFF('hour', v.ARRIVAL_TIME, CURRENT_TIMESTAMP()) AS HOURS_WAITING,
    t.TERMINAL_NAME
FROM RAW.VESSELS v
LEFT JOIN RAW.TERMINALS t ON v.ASSIGNED_TERMINAL = t.TERMINAL_ID
WHERE v.CURRENT_STATUS IN ('ANCHORED', 'BERTHED');

CREATE OR REPLACE DYNAMIC TABLE BERTH_SCHEDULE
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    b.ASSIGNMENT_ID,
    b.VESSEL_ID,
    v.VESSEL_NAME,
    b.TERMINAL_ID,
    t.TERMINAL_NAME,
    b.BERTH_NUMBER,
    b.ARRIVAL,
    b.DEPARTURE,
    b.STATUS,
    DATEDIFF('hour', b.ARRIVAL, COALESCE(b.DEPARTURE, CURRENT_TIMESTAMP())) AS DURATION_HOURS
FROM RAW.BERTH_ASSIGNMENTS b
JOIN RAW.VESSELS v ON b.VESSEL_ID = v.VESSEL_ID
JOIN RAW.TERMINALS t ON b.TERMINAL_ID = t.TERMINAL_ID
WHERE b.DEPARTURE IS NULL;
