-- Port Operations: Cortex Search
USE SCHEMA MANUFACTURING_PORT_OPS.SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE PORT_REGULATIONS_SEARCH
    ON (
        SELECT DOC_ID, TITLE, CATEGORY, CONTENT
        FROM RAW.PORT_REGULATIONS
    )
    WAREHOUSE = CORTEX
    TARGET_LAG = '1 hour'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
    AS (
        SEARCH_COLUMN => 'CONTENT',
        COLUMNS => ['DOC_ID', 'TITLE', 'CATEGORY', 'CONTENT']
    );
