-- Port Operations: ML Models
USE SCHEMA MANUFACTURING_PORT_OPS.ML;

CREATE OR REPLACE VIEW VESSEL_ARRIVAL_INPUT AS
SELECT
    DATE_TRUNC('hour', e.EVENT_TIME) AS DS,
    e.TERMINAL_ID AS SERIES,
    COUNT(*) AS Y
FROM RAW.PORT_EVENTS e
WHERE e.EVENT_TYPE = 'ARRIVAL'
GROUP BY DS, SERIES;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST VESSEL_ARRIVALS_FORECAST(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'VESSEL_ARRIVAL_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION QUEUE_DEPTH_ANOMALY(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'VESSEL_ARRIVAL_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);
